spring:
  profiles:
    active: dev

  logging:
    file: log.xml

  datasource:
    url: jdbc:mysql://localhost:3306/hybris?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true&autoReconnect=true&autoReconnectForPools=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
    maxIdleTime: 5000
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 5000
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
        hbm2ddl:
          import_files:

server:
  port: 2003
  context-path: /cashbackengine
  servlet-path: /
  

db:
 hostname: localhost
 port: 27017
 username: lms
 password: test@123
 name: lmscb
    
